### ISSUE TITLE
Option in CAPM3 that can skip the reimage of the bare metal machine and only create K8s

### ISSUE THREAD

**Issue by niachary** [metal3-io/cluster-api-provider-metal3#1396]
We have a standalone way to reimage the baremetal servers and install certain agents and services on them and are looking at using CAPM3 to create K8s cluster (without reimaging them again using Ironic). Wondering if there exists an option today to achieve the same.

/kind feature

**Comment by Rozzii** [comment]
This a good question, in current CAPM3 workflow there is no way to do this as far as I know, even the way inject the kubeadm scripts/cloud-init data that is sent over to the physical machine is incompatible with this notion of not writing the cloud-init config-2 partition to the local disk of the machine. 

What this would require is to support a different delivery method of the  https://github.com/kubernetes-sigs/cluster-api/tree/main/bootstrap/kubeadm bootstrap provider scripts, and the cloud-init network,user and metadata files  .

Furthermore this would require change in the BMH API behavior as nowadays if you populate the section of the CR manifest that specifies the address of the disk image then BMO will start provisioning that BMH and if I remember correctly until the image address is not provided the provisioning won't start.

What we would need is a separate controller of CAPM3 that e.g. sends the config over SSH or some other protocol.

But there is a issue in the big picture if we make CAPM3 able to pass the kubeadm/cloud-init data on the fly and that is because CAPM3 relies on the status feedback that it receives from the BMH and the BMHs follow the Ironic life cycle very closely thus the only switch to provisioned state when Ironic feels like that the node was provisioned and that is thightly coupled with either attaching a disk image or executing provisioning via IPA that would at least restart the machine but in the current workflow it would als o reimage the machine.

In any case reimageing or re-provisioning images is baked into the workflow from CAPM3 level down to Ironic level.

I assume in your use-case you wouldn't use BMO either right?

I think this is a realistic feature request but this would be big new feature for the community.

/triage needs-information
