### ISSUE TITLE
Manifests are never fetched if test fails before `make test`

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/cluster-api-provider-metal3#1764]
**What steps did you take and what happened:**

https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3-periodic-centos-e2e-integration-test-main/86/

Periodic  e2e fails, or a PR fails.

**What did you expect to happen:**
Manifests are collected, so we can debug the issue easier. These manifest logs fetch BMH, M3DataClaims etc which are key resources for debugging.

**Anything else you would like to add:**
`fetch_logs.sh` is called, but `fetch_manifests.sh` is not.

**Environment:**

- Cluster-api-provider-metal3 version: main
- Environment (metal3-dev-env or other): dev-env

/kind bug

**Comment by tuminoid** [comment]
@smoshiur1237 we did already fix this?

**Comment by smoshiur1237** [comment]
> @smoshiur1237 we did already fix this?

yes It was fixed. and can close this

**Comment by tuminoid** [comment]
Thannks. Link the PR and close please.

**Comment by smoshiur1237** [comment]
The issue was the manifest collection missing from log- The fix was done from dev-env side for manifest and  here also we have added namespace for manifest collection in CAPM3:
https://github.com/metal3-io/cluster-api-provider-metal3/pull/1800
https://github.com/metal3-io/metal3-dev-env/pull/1432
/close
